"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";
import { PortalPage } from "../../../components/portal-shell";

const steps = ["Applicant details", "Authority & request", "Review"];

export default function NewRequestPage() {
  const [step, setStep] = useState(0); const [message, setMessage] = useState("");
  function nextStep(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (step < 2) setStep(step + 1); else setMessage("Demo mode: your request is ready for the payment step."); }
  return <PortalPage><main className="form-page wrap"><div className="bread"><Link href="/">Home</Link><span>›</span><Link href="/request">Submit request</Link><span>›</span><span>New request</span></div><div className="form-layout"><aside className="form-sidebar"><p className="eyebrow"><span className="eyebrow-line" />NEW RTI REQUEST</p><h1>File your request</h1><ol>{steps.map((label, index) => <li className={index === step ? "active" : index < step ? "done" : ""} key={label}><span>{index < step ? "✓" : index + 1}</span>{label}</li>)}</ol><p>Your progress is kept in this browser until the backend is connected.</p></aside><section className="form-card"><p className="form-step">STEP {step + 1} OF 3</p><h2>{steps[step]}</h2><form onSubmit={nextStep}>{step === 0 && <><label htmlFor="name">Full name</label><input id="name" required placeholder="Enter your full name" /><label htmlFor="email">Email address</label><input id="email" type="email" required placeholder="you@example.com" /><label htmlFor="phone">Mobile number</label><input id="phone" inputMode="numeric" required placeholder="10-digit mobile number" /></>}{step === 1 && <><label htmlFor="authority">Public authority</label><select id="authority" required defaultValue=""><option value="" disabled>Select the authority</option><option>Department of Personnel & Training</option><option>Ministry of Home Affairs</option><option>Ministry of Finance</option></select><label htmlFor="request-text">Information requested</label><textarea id="request-text" required maxLength={3000} placeholder="Describe the information you wish to receive. Keep it clear and specific." rows={7} /></>}{step === 2 && <div className="review-box"><h3>Ready to review</h3><p>Before payment, you will be able to review your applicant details, chosen authority, and request text.</p><p className="review-note">No real information is submitted in this frontend demo.</p></div>}<div className="form-actions">{step > 0 && <button className="secondary" type="button" onClick={() => setStep(step - 1)}>Back</button>}<button className="primary" type="submit">{step === 2 ? "Continue to payment" : "Continue"} <span>→</span></button></div>{message && <p className="form-message" role="status">{message}</p>}</form></section></div></main></PortalPage>;
}
